# Generated by Django 4.2.2 on 2023-06-19 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=0)),
                ('changed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
