# Generated by Django 4.2.2 on 2023-06-20 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audioversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('path_to_file', models.CharField(max_length=200)),
                ('changed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
