# Generated by Django 4.2.2 on 2023-06-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioVersion',
        ),
    ]
