# Generated by Django 4.2.2 on 2023-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_audioversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(default='aboba', max_length=200),
            preserve_default=False,
        ),
    ]
