# Generated by Django 4.2.2 on 2023-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=0)),
                ('count_of_audios', models.IntegerField(default=0)),
            ],
        ),
    ]
