# Generated by Django 4.2.2 on 2023-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_audiometa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path_to_file',
            field=models.FileField(upload_to=''),
        ),
    ]
