# Generated by Django 4.2.2 on 2023-06-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_audio_path_to_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='path_to_file',
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(default='', upload_to='', verbose_name='audio_files/'),
            preserve_default=False,
        ),
    ]
