# Generated by Django 4.2.2 on 2023-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_audio_path_to_file_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='file',
        ),
        migrations.AddField(
            model_name='audio',
            name='path_to_file',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
