# Generated by Django 4.2.2 on 2023-06-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_audio_file_audio_path_to_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiometa',
            name='count_of_audios',
        ),
    ]
