# Generated by Django 4.2.2 on 2023-06-24 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_audiometa_changed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFreeTextTaskAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=99999)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_free_text_task_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
